### ISSUE TITLE
Connect to remote Chrome instances

### ISSUE THREAD

**Issue by priithaamer** [joelgriffith/navalia#28]
Currently, this library seems to rely on chrome-launcher when it comes to connecting to chrome instances. Would it make sense to have alternative way of connecting to already running instances during Navalia initialization? I wouldnt mind working on this because i have huge need for this and i _really_ like navalia's api.

I happen to have use case where i have number of VMs running headless chrome and i can connect to them over the remote debugging protocol. It becomes useful when using chrome from AWS Lambda functions, for example.

Anyway, thanks for the fresh approach in browser driver landscape. I've been looking forward to this for some time by now. Cheers!

**Comment by joelgriffith** [comment]
I think this is a fabulous idea, and definitely within the realm of this project! I'd love to see a PR if you're willing to try out a contribution 😄 

There's a few place you can start: the first by adding a parameter to `Navalia`'s constructor to specify where the browsers are. When starting chrome, you can pass in a port for remote debuggers to connect, which is what you'd have to do. As far as the API might go, I think something like:

```
const navalia = new Navalia({
  chromeOptions: {
    remote: ['http://www.my-site.com:1234', 'http://www.my-site.com:4567'],
  }
});
```

Navalia starts Chrome [here](https://github.com/joelgriffith/navalia/blob/master/src/Navalia.ts#L133), so we'll need to alter some utilities to allow passing in an existing chrome instance. There'd also be other work in the "cleanup" portion of the library as well, as Navalia will try and close these on shutdown or when maximums are reached [here](https://github.com/joelgriffith/navalia/blob/master/src/Navalia.ts#L54), which we probably don't want it to do.

Let me know if how I can help guide or give feedback, but definitely say give it a shot! We're open to it!

**Comment by joelgriffith** [comment]
I can take care of all the tedious parts (docs, changelog, releasing), so don't worry about those ceremonious tasks

**Comment by priithaamer** [comment]
Hey, thanks for pointing out where to start! I was reading through the code earlier and it is also easy to follow. Anyway, i will start working on it soon.

**Comment by joelgriffith** [comment]
Hey @priithaamer, just checking in with you on this. I can knock this out if it's a blocker for you?

**Comment by priithaamer** [comment]
Hey, i'm not in a hurry with this. Feel free to work on more urgent issues. Currently, i have my own wrapper for chrome-remote-interface that is quite similar to navalia. However, i would like to use well maintained library eventually and this project here is a perfect replacement.

**Comment by joelgriffith** [comment]
Been a few days! The `Chrome` module now supports this (I'm working on getting it into the `Navalia` Module next).

`npm i --save navalia@1.1.0` 🎉

**Comment by priithaamer** [comment]
Whoa, that was quick! I'll try it out in the next couple of days.
