### ISSUE TITLE
goto with custom header 

### ISSUE THREAD

**Issue by Wykks** [joelgriffith/navalia#33]
Hi !
Thanks for this tool :+1: 
Just requesting a feature: add a way to pass custom headers to `goto`.
Not sure how it works, but there's something about `headers` in `Network.Request`

**Comment by joelgriffith** [comment]
Great idea! I'm thinking something like:

```
chrome.goto('http://www.google.com', { headers: { Authorization: 'abcdefg' } })
```

OR, the other option: 

```
chrome.header('Authorization', 'abcdefg');
chrome.goto()
```

I'm working on adding the latter no matter what, the first can be just sugar over what the `.header` API will look do?

**Comment by joelgriffith** [comment]
I _don't_ have a parameter yet in `goto`, however there's a new API for this here: https://joelgriffith.github.io/navalia/Chrome/header/. You can call it before `goto`:

```
await chrome.header({ Authorization: 'abc:123' });
await chrome.goto('https://www.amazon.com');
```

**Comment by Wykks** [comment]
Oh cool thanks !
