### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by stevenvachon** [joelgriffith/navalia#40]
I actually came across this last week or so and couldn't really figure out what it was. Just now I found out that it's like [chromeless](https://npmjs.com/chromeless) (which is like Nightmare.js), except that it's actually feature complete and not just an empty v1.0

"Navalia" doesn't communicate anything to me and makes me think of some frontend framework, like Aurelia or something.

**Comment by joelgriffith** [comment]
Well put. Honestly I thought "I wonder what Kubernetes means" and came up with this. Longer term I'd like to add more browsers to the library, so I was hesitant to name it something specific... I'm not sure if there's a better name in reality.

**Comment by stevenvachon** [comment]
Perhaps a simpler design would be to have this library as an abstract headless browser lib that depends on "chromeless" and a theoretical "firefoxless".

**Comment by joelgriffith** [comment]
Yeah, I'm starting to come around to that idea. I'll post some more about that as things unfold...
