### ISSUE TITLE
Clear cookies before open page

### ISSUE THREAD

**Issue by Jehanramadhan** [joelgriffith/navalia#41]
Is there any API to clear all cookies?

**Comment by joelgriffith** [comment]
Cookies _should_ be clear by default (the way this app starts is by using `chromeLauncher` which starts with a clean context). I'd be open for whipping up a `clear` method that just drops everything?

**Comment by joelgriffith** [comment]
https://joelgriffith.github.io/navalia/Chrome/clear/ in `1.1.0` 🎉
