### ISSUE TITLE
Chrome window is blank but all tests seem to be working...

### ISSUE THREAD

**Issue by MikeGitIt** [joelgriffith/navalia#43]
I am not sure why my chrome instance is coming up with a blank window when I run navalia code, but it is. I am simply running the examples provided in this article: 
https://codeburst.io/capturing-unused-application-code-2b7594a9fe06

As well, I am also running some code based on the code in that article. Nothing on the screen but tests are passing.  Is there anyone else who has seen this problem and can possibly share what they've done to fix it?  Thanks in advance!

**Comment by joelgriffith** [comment]
Probably dumb question: are you trying to run with a window? By default the Chrome helper runs headless, so there's no window. If it's reporting stats then thing are working, but might need some more info to debug further (Chrome version and so on)

**Comment by MikeGitIt** [comment]
No, actually, it's not a dumb question at all. I was running headless so I added it to my flag parameters as false and, BADABING, BADABANG! Thanks for that nudge in the right direction, wiseguy!

**Comment by MikeGitIt** [comment]
But (there's always a but) it's responding really slow to the methods in my script. Does that timeout flag affect the global timeout settings?

**Comment by joelgriffith** [comment]
Nice! So there's a timeout param on a per-API basis, but a global one as well that you can default with (precedence is given to the API's timeouts vs the global). I'm curios to hear if there's a particular method that is slower than others? Let me know!
