### ISSUE TITLE
Merge into chromeless

### ISSUE THREAD

**Issue by joelgriffith** [joelgriffith/navalia#50]
This issue is to (hopefully) give folks better visibility into the merge status of chromeless. Below is a fairly rough roadmap of what will transpire:

1. Testing and stability of chromeless (~2 weeks or so).
2. Merging of pending PR's + features (week).
3. Moving over of Navalia into chromeless (another week or two).

Again, this is a *really* rough outline of what will happen based upon my current observations at this point in time. It's possible that any one of these points could take longer or happen faster. I'll try and keep folks updated via this issue thread.

As we're transitioning I'll be doing bugfixes and small requests, but the API is pretty locked down at this point in time. Feel free to create an issue in [chromeless](https://github.com/graphcool/chromeless/issues) https://github.com/graphcool/chromeless/issues for any new feature requests. Thanks!

**Comment by elisherer** [comment]
I would gladly help if you need me to. I'm very interested in this project, am working with this to collect images from the development server and running amex' jest plugin for visual unit tests.
Also, would it be possible to publish a new version with the hash bug fix?

**Comment by joelgriffith** [comment]
Definitely! Thanks for the offer! I'll reach out when we start migrating stuff over. `v1.2.0` is published!

**Comment by ls-guillaume-lambert** [comment]
So Navalia will be entirely moved and merged into chromless, and this repo here will be closed?

**Comment by joelgriffith** [comment]
@ls-guillaume-lambert I'll likely keep this repo open for folks to continue using for quite some time. Bugfixes and features _should_ be filed into chromeless as I don't intend to maintain this repo and corresponding npm package in the future

**Comment by ls-guillaume-lambert** [comment]
So we should be looking into using `chromeless` instead, correct?

**Comment by joelgriffith** [comment]
Yup, that's my recommendation! Since we're still in the migration period I'll be fixing bugs in navalia until the day comes where chromeless is at feature-parity. But if I were in your position I'd be making investments in chromeless vs navalia at this point

**Comment by rippo** [comment]
Fantastic. thanks for heads up on chromeless and aws

**Comment by rippo** [comment]
Hey @joelgriffith do you still think Chromeless is the way forward? I really do like it but the project seems to have stalled at the moment and there are a few blocking issues that are not getting released (screenshot paths https://github.com/graphcool/chromeless/issues/282,  waits https://github.com/graphcool/chromeless/issues/279 etc). Is it a case of waiting it out until it gains momentum again?

I have started using Pupeeteer which seems to be actively maintained but the API is basic

Just wondering what your thoughts are on Chromeless? or on Pupeeteer?

Sorry for questions just trying to work out the best options moving forward.

**Comment by joelgriffith** [comment]
Sorry for the delay here!

I've given this a ton of thought, and I think it makes sense to still support/develop navalia. I agree that the puppeteer API is somewhat basic, so having an alternative probably benefits everyone. Chromeless still has place as well, as it's primarily used for running in a lambda context.

I'm going to close this issue and start dusting off this project.
