### ISSUE TITLE
Can you show an example script on how to run navalia on windows?

### ISSUE THREAD

**Issue by rszemplinski** [joelgriffith/navalia#59]
Hi,

I am trying to figure out how to even run this application. I know it runs on headless chrome but I have no idea on how to actually run the test script(s) that I have made.

Thanks!

**Comment by joelgriffith** [comment]
What kind of tests/scripts are you writing? Is it using a framework or anything else?

**Comment by rszemplinski** [comment]
I was able to figure it out and forgot to close out the issue. Sorry!
