### ISSUE TITLE
#wait(Number) crashes with timeout

### ISSUE THREAD

**Issue by castrolol** [joelgriffith/navalia#62]
When I use `await chrome.wait(3000);` the test crashes with the code 

```
 Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

the error persists even if I put the parameter timeout...

```
        await chrome.wait(3000, 5000);
```

```
        await chrome.wait(3000, { timeout: 5000 });
```

```
        chrome = new Chrome({ timeout: 5000 });
```

**Comment by marlonpp** [comment]
hey @castrolol, 
This is a different issue, it's related to Jasmine.
Increasing Jasmine timeout from Jest must do the trick.
```javascript
jest.setTimeout(20000);
```

**Comment by joelgriffith** [comment]
Going to close this for the time being, thanks everyone
