### ISSUE TITLE
RFC: Remove GraphQL?

### ISSUE THREAD

**Issue by joelgriffith** [joelgriffith/navalia#70]
Hey folks,

Looking to dust off this project a bit. Wondering if we should can the GraphQL interface? I'm thinking about a separate project for that since it seems to be not directly related to offering a decent API.

Thoughts?

**Comment by michaelwills** [comment]
Per your comment on https://github.com/joelgriffith/navalia/issues/39#issuecomment-318250421, I favor breaking it out but being available.

**Comment by zgeoff** [comment]
Personally not drawn to using it, but I see it's merit. Offering it as an optional package that plugs straight in seems ideal; I think it makes sense to keep the core purpose of any package lean and focused.
